# Generated by Django 4.2.8 on 2024-02-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_timework_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='day',
        ),
        migrations.CreateModel(
            name='DaysWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, unique=True)),
                ('Programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='api.programme')),
            ],
        ),
    ]
