# Generated by Django 4.2.8 on 2024-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_programme_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayswork',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
    ]
