# Generated by Django 4.2.8 on 2024-02-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dayswork_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayswork',
            old_name='Programme',
            new_name='programme',
        ),
        migrations.RemoveField(
            model_name='timework',
            name='programme',
        ),
        migrations.AddField(
            model_name='timework',
            name='le_jour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workestime', to='api.dayswork'),
        ),
    ]
