# Generated by Django 4.2.8 on 2024-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_programme_dayswork_programme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timework',
            old_name='le_jour',
            new_name='day',
        ),
    ]
