# Generated by Django 4.2.8 on 2024-02-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_le_jour_timework_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timework',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='api.programme'),
        ),
        migrations.AlterField(
            model_name='timework',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DaysWork',
        ),
    ]
