# Generated by Django 4.2.8 on 2024-02-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_timework_programme_alter_timework_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timework',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, null=True),
        ),
    ]
