# Generated by Django 4.2.8 on 2024-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cervice_company_remove_programme_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cervice',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cervice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cervice')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
