# Generated by Django 4.2.8 on 2024-02-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_company_chef_remove_profile_cervice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cervice', models.CharField(max_length=100)),
                ('max_traitement', models.IntegerField(default=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='programme',
            name='cervice',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='cervice',
        ),
        migrations.DeleteModel(
            name='Cervice',
        ),
        migrations.AddField(
            model_name='programme',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AddField(
            model_name='worker',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
    ]
