# Generated by Django 4.2.8 on 2024-02-21 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_service_remove_programme_cervice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='service',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name_cervice',
            new_name='name_service',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='service',
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
        migrations.AddField(
            model_name='programme',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='srvice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='api.service'),
        ),
        migrations.AddField(
            model_name='programme',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TimeWork',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
