# Generated by Django 4.2.8 on 2024-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_profile_phone_alter_profile_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_traitement',
        ),
        migrations.AddField(
            model_name='service',
            name='max_treatment',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time_treatment',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type_treatment',
            field=models.CharField(choices=[('classic', 'Classic'), ('withtime', 'Withtime')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='waiting_time',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
