# Generated by Django 4.2.8 on 2024-02-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_service_max_traitement_service_max_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='day',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='srvice',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='start_time',
        ),
        migrations.AddField(
            model_name='programme',
            name='name_progamme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programme'),
        ),
        migrations.CreateModel(
            name='ServiceDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_days', to='api.programme')),
            ],
        ),
    ]
