# Generated by Django 4.2.8 on 2024-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_programme_day_remove_programme_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_break', models.TimeField(null=True)),
                ('end_time_break', models.TimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programme',
            name='name_progamme',
        ),
        migrations.AddField(
            model_name='programme',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thurday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='service',
            name='programme',
        ),
        migrations.DeleteModel(
            name='ServiceDays',
        ),
        migrations.AddField(
            model_name='programme',
            name='break_time',
            field=models.ManyToManyField(null=True, to='api.break_time'),
        ),
        migrations.AddField(
            model_name='service',
            name='programme',
            field=models.ManyToManyField(null=True, to='api.programme'),
        ),
    ]
