# Generated by Django 4.2.8 on 2024-02-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_service_breaks_time_alter_programme_breaks_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='breaks_time',
            field=models.ManyToManyField(related_name='services', to='api.break_time'),
        ),
    ]
